### ISSUE TITLE
Decentralization potential

### ISSUE THREAD

**Issue by gotjoshua** [fission-codes/auth-lobby#114]
Is it possible to run a "self-hosted" auth lobby from anywhere?

I know, i need to dig into the architecture in more detail... But I'm curious: how much functionality that fission suite now offers is tied to services that are hosted at auth.fission.codes and drive.fission.codes?

What happens if i tweak build and post an altered version, can it access the same data?

**Comment by bmann** [comment]
Drive is a sample app — think of it as a default file browser. You can fork it, embed file browsing in your app, or anything else you like. It operates with permission on a user’s private file system.  

A different app is a different namespace — but you can also give it full permissions on a user’s file system. 

The auth lobby has a number of security features for dealing with permissions and device linking.

We’re working on “app owned logins” aka AOL so that a developer can fully control account creation. In either case, the accounts are DIDs owned by the user.
